version: '3.8'

services:
  video-service:
    build:
      context: ./video-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./video-service/.env
    volumes:
      - ./video-service:/usr/src/app
      - ./video-service/src/config/serviceAccount.json:/usr/src/app/src/config/serviceAccount.json:ro
    command: npm run dev
 