version: '3.8'

services:
  video-service:
    build:
      context: ./video-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=videos
    depends_on:
      - minio
    volumes:
      - ./video-service:/usr/src/app
      - /usr/src/app/node_modules
      - ./video-service/src/config/serviceAccount.json:/usr/src/app/src/config/serviceAccount.json:ro
    command: npm run dev

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=http://10.10.2.2:9001
      - MINIO_SITE_NAME=minio
      - MINIO_SITE_REGION=us-east-1
      - MINIO_DOMAIN=10.10.2.2
      - MINIO_BROWSER=on
      - MINIO_SERVER_URL=http://10.10.2.2:9000
      - MINIO_CORS_ALLOW_ORIGINS=*
      - MINIO_API_CORS_ALLOW_ORIGIN=*
      - MINIO_CORS_ALLOW_METHODS=GET,PUT,POST,DELETE,OPTIONS
      - MINIO_CORS_ALLOW_HEADERS=Accept,Authorization,Content-Type,Content-Length,X-Amz-Date,X-Amz-Content-Sha256,X-Amz-User-Agent,X-Amz-Security-Token
      - MINIO_CORS_EXPOSE_HEADERS=ETag
      - MINIO_CORS_ALLOW_CREDENTIALS=true
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" --address ":9000" /data

volumes:
  minio_data: 